name       : luajit
version    : 2.0.5
release    : 4
source     :
    - https://github.com/LuaJIT/LuaJIT/archive/v2.0.5.tar.gz : 8bb29d84f06eb23c7ea4aa4794dbb248ede9fcb23b6989cbef81dc79352afc97
license    : MIT
summary    : Just-in-time compiler and drop-in replacement for Lua 5.1
component  : programming.library
description: |
    Just-in-time compiler and drop-in replacement for Lua 5.1
build      : |
    %make amalg PREFIX=/usr INSTALL_LIB=$installdir/%libdir%
install    : |
    %make_install PREFIX=/usr INSTALL_LIB=$installdir/%libdir%
    rmdir $installdir/%libdir%/lua/5.1
    rmdir $installdir/%libdir%/lua
    rmdir $installdir/usr/share/lua/5.1
    rmdir $installdir/usr/share/lua
