name       : luajit
version    : 2.1.0
release    : 5
source     :
    - git|https://github.com/LuaJIT/LuaJIT.git : 1c279127050e86e99970100e9c42e0f09cd54ab7
license    : MIT
summary    : Just-in-time compiler and drop-in replacement for Lua 5.1
component  : programming.library
description: |
    Just-in-time compiler and drop-in replacement for Lua 5.1
build      : |
    %make amalg PREFIX=/usr INSTALL_LIB=$installdir/%libdir%
install    : |
    %make_install PREFIX=/usr INSTALL_LIB=$installdir/%libdir%
    rmdir $installdir/%libdir%/lua/5.1
    rmdir $installdir/%libdir%/lua
    rmdir $installdir/usr/share/lua/5.1
    rmdir $installdir/usr/share/lua
